# Working directory (root) where input and output files are stored
wdir: "X:/user/liprandicn/mt-comparison/carleton2022/"

# Temperature data directory
temp_dir: "X:\\user\\dekkerm\\IMAGE_environments"

# Income data directory
gdp_dir: "X:\\user\\dekkerm\\IMAGE_environments"

# Set years range
start_year: 2000
end_year: 2001

# Define project name and scenario
project: "IMPACTS"
scenario: "IMP-SSP5-REF-noGDPIMP-15" #  SSP#_carleton OR SSP#_ERA5 OR IMAGE-scenario-name

# Set adaptation ON or OFF
adaptation: True

reporting_tool: True
regions: "IMAGE26"