# Paths to main directory and temeprature files

wdir: 
temp_dir: 


# Scenario settings 

project: 
scenario:   
start_year: 
end_year: 
region_class:


# Exposure Response Function Settings 

# Using single mean ERF for all zones (True) or all ERFs (False)
single_erf:
# Extrapolate ERFs (True) or keep range as in Burkart 2021 (False)
extrap_erf:
# Calculate mean RR ("mean"), specific (int) or random draw ("random")
draw_type: